<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE library [
<!ELEMENT library (issued)*>
<!ELEMENT issued (bookid, date,borrower)>
<!ATTLIST issued by CDATA "Granville TAFE">
<!ELEMENT bookid (#PCDATA)*>
<!ELEMENT date (#PCDATA)*>
<!ELEMENT borrower (name, id)*>
<!ELEMENT name (#PCDATA)*>
<!ELEMENT id (#PCDATA)*>
]>
<library>
<issued by="Granville TAFE">
<bookid>B001</bookid>
<date>05/05/2020</date>
<borrower>
	<name>Peter</name>
	<id>001</id>
</borrower>
</issued>
<issued by="Miller TAFE">
<bookid>B002</bookid>
<date>06/05/2020</date>
<borrower>
	<name>James</name>
	<id>S001</id>
</borrower>
</issued>
</library>