<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE ProductDetail [
    <!ELEMENT ProductDetail (Product+)>
    <!ELEMENT Product (ProductQuantity, ProductName, ProductPrice)>
    <!ATTLIST Product ID CDATA #REQUIRED>
    <!ELEMENT ProductQuantity (#PCDATA)>
    <!ELEMENT ProductName (#PCDATA)>
    <!ELEMENT ProductPrice (#PCDATA)>
]>
<ProductDetail>
    <Product ID="001">
        <ProductQuantity>300</ProductQuantity>
        <ProductName>Edible oil</ProductName>
        <ProductPrice>90</ProductPrice>
    </Product>
    <Product ID="006">
        <ProductQuantity>50</ProductQuantity>
        <ProductName>Toothbrush</ProductName>
        <ProductPrice>40</ProductPrice>
    </Product>
    <Product ID="009">
        <ProductQuantity>100</ProductQuantity>
        <ProductName>shampoo</ProductName>
        <ProductPrice>20</ProductPrice>
    </Product>
    <Product ID="001">
        <ProductQuantity>100</ProductQuantity>
        <ProductName>Edible oil</ProductName>
        <ProductPrice>90</ProductPrice>
    </Product>
    <Product ID="001">
        <ProductQuantity>30</ProductQuantity>
        <ProductName>Edible oil</ProductName>
        <ProductPrice>90</ProductPrice>
    </Product>
    <Product ID="009">
        <ProductQuantity>50</ProductQuantity>
        <ProductName>shampoo</ProductName>
        <ProductPrice>20</ProductPrice>
    </Product>
    <Product ID="006">
        <ProductQuantity>100</ProductQuantity>
        <ProductName>Toothbrush</ProductName>
        <ProductPrice>40</ProductPrice>
    </Product>
    <Product ID="009">
        <ProductQuantity>200</ProductQuantity>
        <ProductName>shampoo</ProductName>
        <ProductPrice>20</ProductPrice>
    </Product>
    <Product ID="001">
        <ProductQuantity>300</ProductQuantity>
        <ProductName>Edible oil</ProductName>
        <ProductPrice>90</ProductPrice>
    </Product>
    <Product ID="009">
        <ProductQuantity>80</ProductQuantity>
        <ProductName>shampoo</ProductName>
        <ProductPrice>20</ProductPrice>
    </Product>
    <Product ID="001">
        <ProductQuantity>500</ProductQuantity>
        <ProductName>Edible oil</ProductName>
        <ProductPrice>90</ProductPrice>
    </Product>
    <Product ID="006">
        <ProductQuantity>150</ProductQuantity>
        <ProductName>Toothbrush</ProductName>
        <ProductPrice>40</ProductPrice>
    </Product>
    <Product ID="009">
        <ProductQuantity>200</ProductQuantity>
        <ProductName>shampoo</ProductName>
        <ProductPrice>20</ProductPrice>
    </Product>
    <Product ID="004">
        <ProductQuantity>50</ProductQuantity>
        <ProductName>P_Biscuits</ProductName>
        <ProductPrice>10</ProductPrice>
    </Product>
    <Product ID="004">
        <ProductQuantity>50</ProductQuantity>
        <ProductName>P_Biscuits</ProductName>
        <ProductPrice>10</ProductPrice>
    </Product>
    <Product ID="008">
        <ProductQuantity>40</ProductQuantity>
        <ProductName>Cornflakes</ProductName>
        <ProductPrice>60</ProductPrice>
    </Product>
</ProductDetail>