<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<?xml-stylesheet type="text/xsl" href="ProductDetails.xsl"?>
<!DOCTYPE ProductDetail [
    <!ENTITY P001 "001 Edible oil">
    <!ENTITY P004 "004 P_Biscuits">
    <!ENTITY P006 "006 Toothbrush">
    <!ENTITY P008 "008 Cornflakes">
    <!ENTITY P009 "009 Shampoo">

    <!ELEMENT ProductDetail (Product+)>
    <!ELEMENT Product (ProductName, ProductQuantity, ProductPrice)>
    <!ELEMENT ProductName (#PCDATA)>
    <!ELEMENT ProductQuantity (#PCDATA)>
    <!ELEMENT ProductPrice (#PCDATA)>
]>
<ProductDetail>
    <Product>
        <ProductName>&P001;</ProductName>
        <ProductQuantity>300</ProductQuantity>
        <ProductPrice>90</ProductPrice>
    </Product>
    <Product>
        <ProductName>&P006;</ProductName>
        <ProductQuantity>50</ProductQuantity>
        <ProductPrice>40</ProductPrice>
    </Product>
    <Product>
        <ProductName>&P009;</ProductName>
        <ProductQuantity>100</ProductQuantity>
        <ProductPrice>20</ProductPrice>
    </Product>
    <Product>
        <ProductName>&P001;</ProductName>
        <ProductQuantity>100</ProductQuantity>
        <ProductPrice>90</ProductPrice>
    </Product>
    <Product>
        <ProductName>&P001;</ProductName>
        <ProductQuantity>30</ProductQuantity>
        <ProductPrice>90</ProductPrice>
    </Product>
    <Product>
        <ProductName>&P009;</ProductName>
        <ProductQuantity>50</ProductQuantity>
        <ProductPrice>20</ProductPrice>
    </Product>
    <Product>
        <ProductName>&P006;</ProductName>
        <ProductQuantity>100</ProductQuantity>
        <ProductPrice>40</ProductPrice>
    </Product>
    <Product>
        <ProductName>&P009;</ProductName>
        <ProductQuantity>200</ProductQuantity>
        <ProductPrice>20</ProductPrice>
    </Product>
    <Product>
        <ProductName>&P001;</ProductName>
        <ProductQuantity>300</ProductQuantity>
        <ProductPrice>90</ProductPrice>
    </Product>
    <Product>
        <ProductName>&P009;</ProductName>
        <ProductQuantity>80</ProductQuantity>
        <ProductPrice>20</ProductPrice>
    </Product>
    <Product>
        <ProductName>&P001;</ProductName>
        <ProductQuantity>500</ProductQuantity>
        <ProductPrice>90</ProductPrice>
    </Product>
    <Product>
        <ProductName>&P006;</ProductName>
        <ProductQuantity>150</ProductQuantity>
        <ProductPrice>40</ProductPrice>
    </Product>
    <Product>
        <ProductName>&P009;</ProductName>
        <ProductQuantity>200</ProductQuantity>
        <ProductPrice>20</ProductPrice>
    </Product>
    <Product>
        <ProductName>&P004;</ProductName>
        <ProductQuantity>50</ProductQuantity>
        <ProductPrice>10</ProductPrice>
    </Product>
    <Product>
        <ProductName>&P004;</ProductName>
        <ProductQuantity>50</ProductQuantity>
        <ProductPrice>10</ProductPrice>
    </Product>
    <Product>
        <ProductName>&P008;</ProductName>
        <ProductQuantity>40</ProductQuantity>
        <ProductPrice>60</ProductPrice>
    </Product>
</ProductDetail>