<?xml version="1.0" encoding="UTF-8" standalone="yes"?>

<!DOCTYPE list [
<!ELEMENT list (recipe*)>  
<!ELEMENT recipe (author, recipe_name, meal, ingredients, directions)> 
<!ELEMENT author (#PCDATA)>  
<!ELEMENT recipe_name (#PCDATA)>  
<!ELEMENT meal (#PCDATA)>  
<!ELEMENT ingredients (item*)>  
<!ELEMENT item (#PCDATA)>  
<!ELEMENT directions (#PCDATA)> 
]>
<list>
<recipe>
<author>John Smith</author>
<recipe_name>Chocolate Chip Bars</recipe_name>
<meal>Dessert</meal>
<ingredients>
	<item>2/3 Cup butter</item>
	<item>2 Cup brown sugar</item>
	<item>1 tsp vanilla</item>
	<item>1 3/4 Cup all-purpose flour</item>
	<item>1 tsp baking powder</item>
	<item>pinch of salt</item>
	<item>2 eggs</item>
	<item>1/2 Cup chopped nuts</item>
	<item>2 cups (12-oz pkg.) semi-sweet choc. chips</item>
</ingredients>
<directions>Preheat oven to 350 degrees. Melt the butter; add brown sugar and vanilla in a large mixing bowl. Set aside to cool it down. Mix the all-purpose flour, baking powder, and salt and keep it aside.Add eggs to the cooled sugar mixture and beat well. Stir and add dry ingredients, nuts, and chips. Grease a 13-by-9-inch pan with butter.Bake for 30 to 40 minutes until it turns golden brown and then waits for it cool down. After it is completely cool, cut into square pieces and serve.
</directions>
</recipe>
</list>

